#!/bin/bash
clear
export root=$(cd $(dirname "$0");pwd)
cd $root
export multitools=$root/./menu
echo "===================================================================="
echo "*************** Hi!!!Welcome to dark's_multitool *********************"
echo
echo "******* Please Enter your choice****"
echo
echo "******* 1-Cyanogenmod tools ********"
echo
echo "******* 2-ADB Tools *******************"
echo
echo "******* 3-Kernel-Tools *********************"
echo
echo "******* 4-Backup TA partition for Sony or EFS partition on samsung***"
echo
echo "******* 5-Exit*******************************"
echo "===================================================================="
read input
export route=$root/scripts
case $input in
1)$route/cyanogenmod_tools;;
2)$route/ADB_tools;;
3)$route/kernel_menu;;
4)$route/backup;;
5)exit;;
esac
$multitools

        






