#!/bin/bash
clear
echo "Welcome to Samsung EFS partition backup/restore"
echo "Press enter to continue"
read enterkey
echo "1 - Backup EFS partition on your samsung phone"
echo "2 - Restore EFS partition on your samsung phone"
read input2
if [ "$input2" = "1" ]
then
adb shell "su -c '
           mount | grep efs
           exit
           exit'"
echo "Press enter to proceed"
read enterkey
echo "1-Use tar method to backup"
echo "2-Use dd method to backup"
read input3
if [ "$input3" = "1" ]
then
adb shell "su -c '
           tar -cvf mnt/sdcard/efs.tar /efs
           chmod 664 ~/sdcard/efs.tar
           exit
           exit'"
cd ~/dark_multitool1.0/output
adb pull mnt/sdcard/efs.tar
echo "Please find your efs.tar file in your output folder"
elif [ "$input3" = "2" ]
then
echo "Enter the name of the memory block containing the efs partition(ctrl+c to exit)"
read memblock
adb shell "su -c '
           dd if=/dev/block/platform/$memblock of=~/sdcard/efs.img
           chmod 664 ~/sdcard/efs.img
           exit
           exit'"
cd ~/dark_multitool1.0/output
adb pull mnt/sdcard/efs.img
echo "Please find your efs.img file in your output folder"
else 
echo "Please enter a correct value"
fi
elif [ "$input2" = "2" ]
then
echo "1-Use tar method to restore"
echo "2-Use dd method to restore"
read input1
if [ "$input1" = "1" ]
then
echo "Please place your tar file in your input folder of the tool and press enter"
read enterkey
cd ~/dark_multitool1.0/input
adb push efs.tar ~/sdcard/
adb shell "su -c '
           tar -xvf ~/sdcard/efs.tar
           exit
           exit'"
elif [ "$input1" = "2" ]
then
echo "Please place your img file in your input folder of the tool and press enter"
read enterkey
echo "Enter the name of the memory block containing the efs partition(ctrl+c to exit)"
read memblock
cd ~/dark_multitool1.0/input
adb push efs.img ~/sdcard/
adb shell "su -c '
           dd if=~/sdcard/efs.img of=/dev/block/$memblock/efs
           exit
           exit'"
else 
echo "Please enter a correct value"
fi
read enterkey
else 
echo "Enter correct choice"
read enterkey
fi
echo "Done"
echo "Press Enter to continue"
