#!/bin/bash
clear
echo "Welcome to Samsung EFS partition backup/restore"
echo "Press enter to continue"
read enterkey
echo "1 - Backup EFS partition on your samsung phone"
echo "2 - Restore EFS partition on your samsung phone"
read input2
if [ "$input2" = "1" ]
then
adb shell "su -c '
           mount | grep efs
           exit
           exit'"
echo "Please make a note of the partition name"
echo "Press enter to proceed"
read enterkey
echo "1-Use tar method to backup"
echo "2-Use dd method to backup"
read input3
if [ "$input3" = "1" ]
then
adb shell "su -c '
           tar -cvf ~/sdcard/ /efs
           chown sdcard_rw:sdcard_rw ~/sdcard/efs.tar
           chmod 664 ~/sdcard/efs.tar
           exit
           exit'"
cd ~/dark_multitool1.0/output
adb pull /mnt/sdcard/efs.tar
elif [ "$input3" = "2" ]
then
echo "Enter the name of the memory block containing the efs partition"
read $memblock
adb shell "su -c '
           dd if=/dev/block/platform/$memblock/efs of=~/sdcard/efs.img
           chown sdcard_rw:sdcard_rw ~/sdcard/efs.tar
           chmod 664 ~/sdcard/efs.img
           exit
           exit'"
cd ~/dark_multitool1.0/output
adb pull ~/sdcard/efs.img
else 
echo "Please enter a correct value"
fi
elif [ "$input2" = "2" ]
then
echo "1-Use tar method to restore"
echo "2-Use dd method to restore"
read input1
if [ "$input1" = "1" ]
then
cd ~/dark_multitool1.0/input
adb push efs.tar ~/sdcard/
adb shell "su -c '
           tar -xvf ~/sdcard/efs.tar
           exit
           exit'"
elif [ "$input1" = "2" ]
then
cd ~/dark_multitool1.0/input
adb push efs.img ~/sdcard/
adb shell "su -c '
           dd if=~/sdcard/efs.img of=/dev/block/$memblock/efs
           exit
           exit'"
else 
echo "Please enter a correct value"
fi
read enterkey
else 
echo "Enter correct choice"
read enterkey
fi
echo "Done"
echo "Press Enter to continue"
