#!/bin/bash
clear
export root=$(cd $(dirname "$0");pwd)
export multitools=$root/import_lib
echo "Press 1 to install the necessary build packages for cyanogenmod"
echo "Press 2 if you are getting JDK 1.6 required error while compiling cyanogenmod"
read input
case $input in

1 ) echo "****************This will import the necessary packages in order to compile cyanogenmod***********************"
    echo
    echo
    sudo apt-get install git-core gnupg flex bison gperf libsdl1.2-dev libesd0-dev libwxgtk2.8-dev squashfs-tools build-essential zip curl libncurses5-dev zlib1g-dev openjdk-6-jre openjdk-6-jdk pngcrush schedtool libxml2 libxml2-utils xsltproc
    echo "Are you on a 64-bit system?(y/n)"
    read answer
    if [ "$answer" = "y" ]
    then
    sudo apt-get install g++-multilib gcc-multilib lib32ncurses5-dev lib32readline-gplv2-dev lib32z1-dev
    echo "Installed the necesary build packages"
    else $multitools 
    fi;
    read;;
2 ) sudo apt-get purge openjdk-\* icedtea-\* icedtea6-\*
    sudo add-apt-repository ppa:webupd8team/java
    sudo apt-get update && sudo apt-get install oracle-java6-installer
    echo "Correct Java version has been installed!!!!!!!!!!!!!!!!!";
    read;;
esac



