#!/bin/bash
export root=$(cd $(dirname "$0");pwd)
echo "1- Import pre-built tools required for compiling cyanogenmod"
echo "2- Prepare the device specific code"
echo "3- Import device proprietary blobs(You have to connect your device to the computer for this to work)"
read input
case $input in
1) cd ~/$directory_name/vendor/cm
./get-prebuilts;;
2) cd ~/$directory_name
   source build/envsetup.sh
   breakfast $codename;;
3). /$root/import_deviceblobs;
  read;;
esac

