#!/bin/bash
clear
source ~/dark_multitool1.0/scripts/config
echo "Current defconfig name : $config_name"
echo "Current toolchain : $toolchain"
echo "1-Get the source code(make sure you have set up git)"
echo
echo "2-Checkout the source code"
echo
echo "3-Build zImage"
echo
echo "4-exit"
read input
case $input in
1)clear
echo "Please enter the name of the kernel source repository"
echo
echo "For eg: https://android.googlesource.com/device/lge/mako-kernel"
read source_name
cd ~/$kerneldir_name
git clone $source_name
echo "Please rename the downloaded kernel source to kernel so that the tool can detect it"
echo "Press Enter to continue"
read enterkey;;
2)clear
cd ~/$kerneldir_name/kernel
rev=git log kernel
echo "Latest commit revision is $rev"
cd ~/kerneldir_name/kernel/kernel_msm
git checkout "$rev"
echo "Press enter to continue"
read enterkey;;
3)echo "Please enter a new defconfig name"
  read config_name
  TARGET_KEY="config_name"
  REPLACEMENT_VALUE="$config_name"
  sed -i "s@\($TARGET_KEY *= *\).*@\1$REPLACEMENT_VALUE@" ~/dark_multitool1.0/scripts/config
  cd ~/$kerneldir_name/kernel
  ./kernel-tools/toolchain_selector
  echo "Press enter to import the defconfig for your device"
  read enterkey
  ARCH=arm CROSS_COMPILE=$HOME/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make $config_name
  echo "zImage will be compiled now and it might take a long time"
  echo "Press Enter to continue"
  read enterkey
  ARCH=arm CROSS_COMPILE=~/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make -j$(grep -c ^processor /proc/cpuinfo)
  echo "Please find zImage in arch/arm/boot folder of your kernel directory"
  echo "Press enter to continue"
  read enterkey;;
4)exit;;
esac

