#!/bin/bash
clear
source ~/multitool1.0/scripts/config
if [ -z "$config_name" ]
then
echo "Please enter your defconfig name before proceeding"
echo
echo "For eg: for Xperia Play it is semc_zeus_defconfig"
read config_name
TARGET_KEY="config_name"
REPLACEMENT_VALUE="$config_name"
sed -i "s@\($TARGET_KEY *= *\).*@\1$REPLACEMENT_VALUE@" ~/multitool1.0/scripts/config
break
else
echo "Please Enter a choice"
echo
echo "1-Create zImage for Xperia Play/Xperia L/Xperia Arc/Xperia ArcS/Ray/Neo"
echo
echo "2-Create zImage for Xperia S/Xperia SL/Ion/Acro S"
echo
echo "3-Create zImage for Xperia T/ TX/ V"
echo
echo "4-Create zImage for Xperia SP"
echo
echo "5-Create zImage for Xperia Z/ ZL/ Tablet Z/ ZR"
echo
echo "6-Create zImage for Xperia Z1/ Z Ultra"
echo
echo "7-Change defconfig name"
echo
echo "8-Change toolchain"
echo
echo "9-exit"
read input
case $input in
1)clear
  ./kernel-tools/toolchain_selector
  cd ~/$kerneldir_name/kernel
  echo "Recommended toolchain is GCC 4.6 Linaro"
  echo 
  echo "Press enter to import the defconfig for your device"
  read enterkey  
  make ARCH=arm CROSS_COMPILE=home/soch/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make $config_name
  echo "zImage will be compiled now and it might take a long time"
  echo "Press Enter to continue or any other key+Enter to exit"
  read enterkey
  make ARCH=arm CROSS_COMPILE=home/soch/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make;;
2)clear
  ./kernel-tools/toolchain_selector
  cd ~/$kerneldir_name/kernel
  echo "Recommended toolchain is GCC 4.7"
  echo
  echo "Press enter to import the defconfig for your device"
  read enterkey 
  make ARCH=arm CROSS_COMPILE=$HOME/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make $config_name
  echo "zImage will be compiled now and it might take a long time"
  echo "Press Enter to continue or any other key+Enter to exit"
  read enterkey
  ARCH=arm CROSS_COMPILE=$HOME/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make;
  echo "Press enter to continue"
  read enterkey;;
3)clear
  ./kernel-tools/toolchain_selector
  cd ~/$kerneldir_name/kernel
  echo "Recommended toolchain is GCC 4.6 Linaro"
  echo
  echo "Press enter to import the defconfig for your device"
  read enterkey
  ARCH=arm CROSS_COMPILE=$HOME/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make $config_name 
  echo "zImage will be compiled now and it might take a long time"
  echo "Press Enter to continue or any other key+Enter to exit"
  read enterkey
  ARCH=arm CROSS_COMPILE=$HOME/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make;;
4)clear
  ./kernel-tools/toolchain_selector
  cd ~/$kerneldir_name/kernel
  echo "Recommended toolchain is GCC 4.7"
  echo
  echo "Press enter to import the defconfig for your device"
  read enterkey 
  ARCH=arm CROSS_COMPILE=$HOME/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make $config_name  
  echo "zImage will be compiled now and it might take a long time"
  echo "Press Enter to continue or any other key+Enter to exit"
  read enterkey
  ARCH=arm CROSS_COMPILE=$HOME/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make;;
5)clear
  ./kernel-tools/toolchain_selector
  cd ~/$kerneldir_name/kernel
  echo "Recommended toolchain is GCC 4.7"
  echo
  echo "Press enter to import the defconfig for your device"
  read enterkey
  ARCH=arm CROSS_COMPILE=$HOME/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make $config_name
  echo "zImage will be compiled now and it might take a long time"
  echo "Press Enter to continue or any other key+Enter to exit"
  read enterkey
  ARCH=arm CROSS_COMPILE=~/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make;;
6)clear
  ./kernel-tools/toolchain_selector
  cd ~/$kerneldir_name/kernel
  echo "Recommended toolchain is GCC 4.7"
  echo
 echo "Press enter to import the defconfig for your device"
  read enterkey
  ARCH=arm CROSS_COMPILE=~/$kerneldir_name/$toolchain- make $config_name
  echo "zImage will be compiled now and it might take a long time"
  echo "Press Enter to continue or any other key+Enter to exit"
  read enterkey
  ARCH=arm CROSS_COMPILE=~/$kerneldir_name/android_prebuilt_toolchains/$toolchain- make;;
7)echo "Please enter a new defconfig name"
  read config_name
  TARGET_KEY="config_name"
  REPLACEMENT_VALUE="$config_name"
  sed -i "s@\($TARGET_KEY *= *\).*@\1$REPLACEMENT_VALUE@" ~/multitool1.0/scripts/config;;
8)./kernel-tools/toolchain_selector;;
9)exit;;
esac
fi

  
  
  

