#!/bin/bash
clear
export root=$(cd $(dirname "$0");pwd)
export multitools=$root/Sony
source ~/dark_multitool1.0/scripts/config
export PATH=$PATH:$HOME/bin
echo "----------Sony Kernel Tools----------"
echo 
echo "What would you like to do??????"
echo
echo "1-Unpack Kernel Source"
echo
echo "2-Extract kernel.sin file from ftf file"
echo
echo "3-Extract kernel.sin file to get zImage & Ramdisk"
echo
echo "4-Compile Zimage from source"
echo
echo "5-Make dt.img(for xperia z1 and z ultra)"
echo
echo "6-Make kernel.elf or boot.img from zImage and Ramdisk"
echo
echo "7-Dry run(Test your kernel.elf/boot.img)"
echo
echo "8-Exit"
read input
case $input in
1)clear
  echo "Please place a copy of the downloaded source tar.bz2 file in the input folder of the tool"
  echo "Press Enter to proceed with unpacking"
  cd ~/dark_multitool1.0/kernel-tools/
  python extractor.py $kerneldir_name
  echo "Please find the unpacked source in your kernel work directory"
  echo "Press enter to continue"
  read enterkey;;
2)clear
  echo "Place a copy of the ftf file in your kernel work directory"
  echo
  echo "Press enter to extract kernel.sin"
  read enterkey
  cd ~/$kerneldir_name
  unzip *.ftf kernel.sin
  echo "Please find kernel.sin in your kernel work directory"
  echo "Press enter to continue"
  read enterkey;;
3)clear
  echo "Place kernel.sin in your kernel work directory"
  echo
  echo "Press enter to unpack kernel.sin"
  read enterkey
  cd ~/$kerneldir_name
  unpack-kernelsin.pl kernel.sin 
  echo "Please find zimage and ramdisk from kernel.sin in your kernel work directory"
  echo "Press enter to continue"
  read enterkey;;
4)clear
echo "Please maximize your terminal window before proceeding(Press Enter)"
read enterkey
./kernel-tools/Sony_buildzimage;;  
5)clear
echo "generating device tree..."
dtbTool -o dt.img -s 2048 -p ~/$kerneldir_name/kernel/scripts/dtc/ ~/$kerneldir_name/kernel/arch/arm/boot/
echo "Please find dt.img in arch/arm/boot folder of your kernel source folder(Press Enter to continue)"
read enterkey;;
6)./kernel-tools/Sony_build;;
7)clear
echo "Note : This option might not work if your device cannot hotboot kernel.elf/boot.img"
echo "Place your boot.img or kernel.elf in the input folder of the tool"
cd ~/dark_multitool1.0/input
echo "Enter what you wanna test(eg. for kernel.elf type kernel.elf"
read tester
echo "Now connect your phone in fastboot mode and press Enter"
read enterkey
fastboot boot $tester;;
8). ~/dark_multitool1.0/scripts/kernel_menu;;
esac
$multitools
  
