#!/bin/bash
clear
source ~/multitool1.0/scripts/config
cd ~/$kerneldir_name/android_prebuilt_toolchains/
toolchain_name[0]="Android arm eabi 4.4.3"
toolchain_name[1]="GCC 4.6 Linaro"
toolchain_name[2]="GCC 4.7"
toolchain_path[0]="arm-eabi-4.4.3/bin/arm-eabi"
toolchain_path[1]="arm-eabi-linaro-4.6.2/bin/arm-eabi"
toolchain_path[2]="arm-linux-androideabi-4.7/bin/arm-linux-androideabi"

count=1
echo "Please select the toolchain you wish to use"
for name in "${toolchain_name[@]}";
do
echo "$count-""$name"
count=$[count+1];
done
echo "$count-exit"
read input
input=$[input-1]
TARGET_KEY="toolchain"
REPLACEMENT_VALUE="${toolchain_path[$input]}"
sed -i "s@\($TARGET_KEY *= *\).*@\1$REPLACEMENT_VALUE@" ~/multitool1.0/scripts/config
echo "Press Enter to continue"
read enterkey




 
