#!/bin/bash
directory_name=pichu
codename=nozomi
kerneldir_name=pikachu/pikachu
config_name=fusion3_yuga_defconfig
export git_directory=lulu/dark_multitool1.0
export git_username=
export git_repo=
export git_branch_name=master
export toolchain=
export directory_name
export codename
export kerneldir_name
export config_name

