#!/bin/bash
directory_name=pichu
codename=nozomi
kerneldir_name=pikachu/pikachu
config_name=fuji_nozomi_defconfig
toolchain=arm-linux-androideabi-4.7/bin/arm-linux-androideabi
export directory_name
export codename
export kerneldir_name
export config_name
export toolchain
