#!/bin/bash
export root=$(cd $(dirname "$0");pwd)
export multitools=$root/cyanogenmod_tools
clear
echo
echo "********************Welcome to Cyanogenmod Tools********************"
echo
echo "===================================================================="
echo
echo "What do you want to do???????"
echo
echo "1-Install the necessary libraries"
echo "2-Initialize your repository and get the AOSP source code"
echo "3-Get the prebuilt apps or device propietary blobs to compile cyanogenmod"
echo "*Note:Can only be done after getting the source code(option-2)*"
echo "4-Change/define working directory and device codename"
echo
echo "5.exit"
echo "====================================================================="

read input
case $input in
1) clear; 
  ./Cyanogenmod_scripts/import_libraries/import_lib;;
2) clear;
  ./Cyanogenmod_scripts/repo_initialize/repo_init;;
3)clear;
  ./Cyanogenmod_scripts/import_libraries/import_prebuilts;;
4)clear;
  cd ~/multitool1.0/scripts/
  ./global_info;;
5) exit;;
esac
$multitools

