#!/bin/bash
clear
echo "1 - Download GIT package on your linux"
echo
echo "2 - Change directory where you want to initialize git"
echo
echo "3 - Git repository setup(New git setup/Changes to old git setup)"
echo
echo "4 - Update your local and remote git repository"
echo
echo "5 - Commit your additions/deletions"
echo
echo "6 - Push/Pull to/from yout github repository"
echo
echo "7 - Download any repository using GIT"
echo
echo "8-exit"
read input
case $input in
1)sudo apt-get install git;;
2)clear
echo "Enter name of the directory you want GIT to be initialized"
read input1
TARGET_KEY="git_directory"
REPLACEMENT_VALUE="$input1"
sed -i "s@\($TARGET_KEY *= *\).*@\1$REPLACEMENT_VALUE@" ~/multitool1.0/scripts/config;;
3)./Git_tools/Git_init;;
4)./Git_tools/Git_add;;
5)./Git_tools/Git_commit;;
6)./Git_tools/Git_op;;
7)clear
echo "Enter the github URL of the repository you want to clone"
read URL
git clone $URL
echo "Press Enter to continue"
read enterkey;;
8)exit;;
esac



