#!/bin/bash
clear
echo "--------Before you proceed please create a work directory for your files-------"
echo 
echo "You can create nested directories(for eg:android/system).Enter the directory name in the same format given below"
echo
echo "Directory name for one directory under home folder or parent directory/child directory/...)"
echo "***************************************************************************************"
read directory_name
mkdir -p ~/$directory_name
echo "Enter the device codename"
echo "Note: Every device has a code name. If you are not sure what it is then google it out"
echo "For example(Sony Xperia S code name is nozomi Xperia mini Pro sk17i-mango) etc"
read codename
TARGET_KEY1="directory_name"
REPLACEMENT_VALUE1="$directory_name"
sed -i "s@\($TARGET_KEY1 *= *\).*@\1$REPLACEMENT_VALUE1@" config
TARGET_KEY2="codename"
REPLACEMENT_VALUE2="$codename"
sed -i "s/\($TARGET_KEY2 *= *\).*/\1$REPLACEMENT_VALUE2/" config
read enterkey




