#!/bin/bash
clear
echo "=============================================="
echo 
echo "******* Welcome to kernel-tools **************"
echo
echo "Disclaimer: Please note that this section is only meant for you"
echo "if you know how to compile a kernel from its source...I do not"
echo "take responsibility if your kernel doesnt boot up"
echo "or is compiled wrongly..Nor will the tool do everything for you"
echo "This section only provides you with tools and utilities to free you"
echo "from a few tasks required when you are compiling a kernel from its source...."
echo
source ~/dark_multitool1.0/scripts/config
cp ~/dark_multitool1.0/bin/* $HOME/bin
echo "Reading config................"
echo "Current kernel work directory = $kerneldir_name"
echo
echo "******* Please select what you want to do ********"
echo
echo "1 - Define/change work directory for your kernel "
echo
echo "2 - To work on Sony kernel"
echo
echo "3 - To work on Nexus kernel"
echo
echo "4 - To work on Samsung kernel"
echo
echo "5 - Download toolchains"
echo
echo "6 - Unpack boot.img to get zImage and Ramdisk"
echo 
echo "7 - Unpack or Repack ramdisk"
echo
echo "8 - Exit"
read input
case $input in
1) echo "--------Before you proceed please create a work directory for your files-------"
   echo 
   echo "You can create nested directories(for eg:android/system).Enter the directory name in the same format given below"
   echo
   echo "Directory name for one directory under home folder or parent directory/child directory/...)"
   echo "***************************************************************************************"
   read kerneldir_name
   mkdir -p ~/$kerneldir_name
   TARGET_KEY="kerneldir_name"
   REPLACEMENT_VALUE="$kerneldir_name"
   sed -i "s@\($TARGET_KEY *= *\).*@\1$REPLACEMENT_VALUE@" ~/dark_multitool1.0/scripts/config;
   read;;
2)./kernel-tools/Sony;;
3)./kernel-tools/nexus_kernel;;
4)./kernel-tools/samsung;;
5)echo "A few toolchains will be downloaded"
  echo "Press enter to continue"
  read enterkey
  cd
  git clone https://github.com/Smk1989/android_toolchains.git
  echo "Press enter to continue"
  read enterkey;; 
6)clear
echo "Place boot.img in the input folder of the tool"
echo
echo "Press Enter to continue"
read enterkey
cd ~/dark_multitool1.0/input
unpack-bootimg.pl boot.img
rm *.img
mv ~/dark_multitool1.0/input/* ~/dark_multitool1.0/output
echo "Done..please find your extracted zImage and ramdisk in the output folder of the tool(press enter)"
read enterkey;;
7)./kernel-tools/unpack_repack;;
8)exit;;
esac

  
   
   
   
