#!/bin/bash
clear
export root=$(cd $(dirname "$0");pwd)
export multitools=$root/repo_init
mkdir -p ~/bin
cd ~/dark_multitool1.0/scripts/
./global_info
echo "Enter build number of the Cyanogenmod source you want to compile"
echo "1-cm-7.0.0"
echo "2-cm-7.0.1"
echo "3-cm-7.0.3"
echo "4-cm-9.0.0"
echo "5-cm-9.1.0"
echo "6-cm-10.1"
echo "7-cm-10.2"
echo "8-Something else(Please go to http://wiki.cyanogenmod.org/ and enter the Cyanogenmod source name you wish to get)"
read user_input
case $user_input in
1 ) user_choice="cm-7.0.0";;
2 ) user_choice="cm-7.0.1";;
3 ) user_choice="cm-7.0.3";;
4 ) user_choice="cm-9.0.0";;
5 ) user_choice="cm-9.1.0";;
6 ) user_choice="cm-10.1";;
7 ) user_choice="cm-10.2";;
8 ) echo "Enter the name of the cyanogenmod source you want to get"
    echo "*************warning*****************"
    echo "Enter the name of the source as the exact branch name from cm source in github(eg.ics or cm-7.0.2.1)"
    read user_choice;;
esac
cd ~/$director_name
echo "*********Initializing repo**********"
curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
export PATH=${PATH}:~/bin
repo init -u git://github.com/CyanogenMod/android.git -b $user_choice
echo $user_choice
echo "CyanogenMod source repository has been initialized"
echo "*******************warning***************"
echo "You will now proceed to downloading of the source code"
echo "Android Source code is huge(~10GB) and it will take a long time to download(hours to days)depending on your internet speed"
echo "Tip:If downloading stops or gets stuck or worst case if laptop shuts down..Then just hit CTRL+Z,navigate to your work folder(cd work folder name) and type 'repo sync'"
echo "Do you wish to continue(y/n)"
read user_confirm
if [ "$user_confirm" = "y" ]
then
repo sync
else
$multitools
fi
$multitools



